gcp_CE_Machine_Type     = "e2-medium"
gcp_vpc_network         = "kums-vpcnetwork"
gcp_vpc_subnetwork      = "kums-vpcsubnetwork"
gcp_region              = "us-west1"
gcp_vpc_targettags      = "lb-backend"
gcp_vm_instanceTemplate = "instance-template-kums"